name: ci
on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format-20
      - name: Check formatting
        env:
          CLANG_FORMAT: clang-format-20
        run: tools/check-format.sh
